## Step 1: download the Flight data from 2008

+ We're interested in predicting Departure Delays!

http://stat-computing.org/dataexpo/2009/the-data.html

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("../../DS-SF-32/dataset/2008.csv").fillna(0)

In [3]:
pd.options.display.max_columns = 999

df.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0        2225            WN        335  N712SW              128.0   
1        1000            WN       3231  N772SW              128.0   
2         750            WN        448  N428WN               96.0   
3        1100            WN       1746  N612SW               88.0   
4        1925            WN       3920  N464WN               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     78.0      -6.0      -4.0    IND  BWI       515     3.0   
4            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                0         0           0.0           0.0   
1     10.0          0                0         0           0.0           0.0   
2     17.0          0                0         0           0.0           0.0   
3      7.0          0                0         0           0.0           0.0   
4     10.0          0                0         0           2.0           0.0   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       0.0            0.0                0.0  
1       0.0            0.0                0.0  
2       0.0            0.0                0.0  
3       0.0            0.0                0.0  
4       0.0            0.0               32.0

In [4]:
df.shape

(7009728, 29)

### This dataset is WAY TOO BIG for the get_dummies function

+ Feel free to test it out and eventually use the "interrupt" function when you get bored
+ Hey maybe it still works? Who knows. It took a while for me. 

In [5]:
# pd.get_dummies(df[['TailNum', 'Origin', 'Dest']])

### Let's first investigate the String Vars here

In [8]:
df[['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']].head(10)

UniqueCarrier TailNum Origin Dest CancellationCode
0            WN  N712SW    IAD  TPA                0
1            WN  N772SW    IAD  TPA                0
2            WN  N428WN    IND  BWI                0
3            WN  N612SW    IND  BWI                0
4            WN  N464WN    IND  BWI                0
5            WN  N726SW    IND  JAX                0
6            WN  N763SW    IND  LAS                0
7            WN  N428WN    IND  LAS                0
8            WN  N689SW    IND  MCI                0
9            WN  N648SW    IND  MCI                0

## We can use the Label Encoder to map the Strings to numbers!

+ THESE ARE NOT DUMMY VARIABLES
+ Note the fit vs fit_transform function

In [13]:
from sklearn.preprocessing import  LabelEncoder

le = LabelEncoder()  # initialize a new label encoder

le.fit(df['UniqueCarrier'].head(10))

le.transform(df['UniqueCarrier'].head(10))



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
df['UniqueCarrier'].unique()   # note .unique finds unique rows?

array(['WN', 'XE', 'YV', 'OH', 'OO', 'UA', 'US', 'DL', 'EV', 'F9', 'FL',
       'HA', 'MQ', 'NW', '9E', 'AA', 'AQ', 'AS', 'B6', 'CO'], dtype=object)

In [24]:
uniqueUCValues = df['UniqueCarrier'].unique().tolist()

le.fit(uniqueUCValues)

le.transform(df['UniqueCarrier'].unique().tolist())  

array([17, 18, 19, 13, 14, 15, 16,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,
        3,  4,  5])

In [60]:
le = LabelEncoder()

print df['UniqueCarrier'].unique().tolist()

# fit and return labels in one step!
le.fit_transform(df['UniqueCarrier'].unique().tolist()).tolist()

['WN', 'XE', 'YV', 'OH', 'OO', 'UA', 'US', 'DL', 'EV', 'F9', 'FL', 'HA', 'MQ', 'NW', '9E', 'AA', 'AQ', 'AS', 'B6', 'CO']


[17, 18, 19, 13, 14, 15, 16, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5]

In [84]:
le.fit_transform(df['UniqueCarrier'])

array([17, 17, 17, ...,  6,  6,  6])

### TASK: How can you transform all character variables into numbers? 

+ Take 10 minutes to work with your partner

In [78]:
df2[['TailNum', 'DepDelay']].apply(lambda x: str(x), axis=1).head()

0    TailNum     N712SW\nDepDelay         8\nName: ...
1    TailNum     N772SW\nDepDelay        19\nName: ...
2    TailNum     N428WN\nDepDelay         8\nName: ...
3    TailNum     N612SW\nDepDelay        -4\nName: ...
4    TailNum     N464WN\nDepDelay        34\nName: ...
dtype: object

In [79]:
df2.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [76]:
df2['DepDelay'].head()

0     8.0
1    19.0
2     8.0
3    -4.0
4    34.0
Name: DepDelay, dtype: float64

In [36]:
# 'UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode'

In [81]:
stringMask = (df.dtypes==np.object).tolist()
stringMask[0:5]

[False, False, False, False, False]

In [88]:
df2 = df.head(10000)

In [98]:
# use LabelEncoder to get numbers that represent categories
le = LabelEncoder()  # initialize a new label encoder

stringCols = ['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']


In [133]:
# try a for loop version !
df3 = df.head(10000).copy()
df3.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0        2225            WN        335  N712SW              128.0   
1        1000            WN       3231  N772SW              128.0   
2         750            WN        448  N428WN               96.0   
3        1100            WN       1746  N612SW               88.0   
4        1925            WN       3920  N464WN               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     78.0      -6.0      -4.0    IND  BWI       515     3.0   
4            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                0         0           0.0           0.0   
1     10.0          0                0         0           0.0           0.0   
2     17.0          0                0         0           0.0           0.0   
3      7.0          0                0         0           0.0           0.0   
4     10.0          0                0         0           2.0           0.0   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       0.0            0.0                0.0  
1       0.0            0.0                0.0  
2       0.0            0.0                0.0  
3       0.0            0.0                0.0  
4       0.0            0.0               32.0

In [139]:
for column in stringCols:
    step1 = le.fit_transform(df3[column])
    print step1
    df3[column] = step1


[0 0 0 ..., 0 0 0]
[413 470 217 ...,  84  84  84]
[22 22 23 ..., 28 28 28]
[61 61 10 ..., 55 55 55]
[0 0 0 ..., 0 0 0]


In [140]:
df3.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime  UniqueCarrier  FlightNum  TailNum  ActualElapsedTime  \
0        2225              0        335      413              128.0   
1        1000              0       3231      470              128.0   
2         750              0        448      217               96.0   
3        1100              0       1746      324               88.0   
4        1925              0       3920      253               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay  Origin  Dest  Distance  \
0           150.0    116.0     -14.0       8.0      22    61       810   
1           145.0    113.0       2.0      19.0      22    61       810   
2            90.0     76.0      14.0       8.0      23    10       515   
3            90.0     78.0      -6.0      -4.0      23    10       515   
4            90.0     77.0      34.0      34.0      23    10       515   

   TaxiIn  TaxiOut  Cancelled  CancellationCode  Diverted  CarrierDelay  \
0     4.0      8.0          0                 0         0           0.0   
1     5.0     10.0          0                 0         0           0.0   
2     3.0     17.0          0                 0         0           0.0   
3     3.0      7.0          0                 0         0           0.0   
4     3.0     10.0          0                 0         0           2.0   

   WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay  
0           0.0       0.0            0.0                0.0  
1           0.0       0.0            0.0                0.0  
2           0.0       0.0            0.0                0.0  
3           0.0       0.0            0.0                0.0  
4           0.0       0.0            0.0               32.0

In [97]:
# axis=0 means go by values in a column
# axis=1 would mean go by values in a row
char_to_num = df2[stringCols].apply(lambda x: le.fit_transform(x), axis=0)

In [95]:
char_to_num.head()

UniqueCarrier  TailNum  Origin  Dest  CancellationCode
0              0      413      22    61                 0
1              0      470      22    61                 0
2              0      217      23    10                 0
3              0      324      23    10                 0
4              0      253      23    10                 0

In [108]:
df2[stringCols] = char_to_num  

In [110]:
df2.loc[:, stringCols] = char_to_num
df2[stringCols].head()

UniqueCarrier  TailNum  Origin  Dest  CancellationCode
0              0      413      22    61                 0
1              0      470      22    61                 0
2              0      217      23    10                 0
3              0      324      23    10                 0
4              0      253      23    10                 0

### Now as a replacement for get_dummies we have OneHotEncoder

+ BUT YOU NEED TO SPECIFY WHICH VARIABLES ARE CATEGORICAL
+ Could we use "integer" type as a proxy for that?
  - I think no, because we have actual integers!
  - Reid says yes, because those are probably categorical anyway!

In [131]:
df2.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier          int64
FlightNum              int64
TailNum                int64
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                 int64
Dest                   int64
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode       int64
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [157]:
# move non-categorial variables back to float
nonCategorical = ['CRSDepTime', 'CRSArrTime', 'Distance']
# for column in nonCategorical:
#         df2[column].apply(float)  # same as apply(lambda x: float(x))
# also df2['CRSDepTime'].astype(float)

# pandas prefers .loc
df2.loc[:, nonCategorical] = df2[nonCategorical].astype(float)
df2.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0      1955.0   2211.0   
1  2008      1           3          4    754.0       735.0   1002.0   
2  2008      1           3          4    628.0       620.0    804.0   
3  2008      1           3          4    926.0       930.0   1054.0   
4  2008      1           3          4   1829.0      1755.0   1959.0   

   CRSArrTime  UniqueCarrier  FlightNum  TailNum  ActualElapsedTime  \
0      2225.0              0        335      413              128.0   
1      1000.0              0       3231      470              128.0   
2       750.0              0        448      217               96.0   
3      1100.0              0       1746      324               88.0   
4      1925.0              0       3920      253               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay  Origin  Dest  Distance  \
0           150.0    116.0     -14.0       8.0      22    61     810.0   
1           145.0    113.0       2.0      19.0      22    61     810.0   
2            90.0     76.0      14.0       8.0      23    10     515.0   
3            90.0     78.0      -6.0      -4.0      23    10     515.0   
4            90.0     77.0      34.0      34.0      23    10     515.0   

   TaxiIn  TaxiOut  Cancelled  CancellationCode  Diverted  CarrierDelay  \
0     4.0      8.0          0                 0         0           0.0   
1     5.0     10.0          0                 0         0           0.0   
2     3.0     17.0          0                 0         0           0.0   
3     3.0      7.0          0                 0         0           0.0   
4     3.0     10.0          0                 0         0           2.0   

   WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay  
0           0.0       0.0            0.0                0.0  
1           0.0       0.0            0.0                0.0  
2           0.0       0.0            0.0                0.0  
3           0.0       0.0            0.0                0.0  
4           0.0       0.0            0.0               32.0

In [198]:
import numpy as np

categoricalMask = (df2.dtypes==np.int64).tolist()
categoricalMask

[True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False]

In [127]:
# y = df['DepDelay']
# df.drop(['DepDelay'], axis = 1, inplace = True, errors = 'ignore')

In [129]:
df2.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime  UniqueCarrier  FlightNum  TailNum  ActualElapsedTime  \
0        2225              0        335      413              128.0   
1        1000              0       3231      470              128.0   
2         750              0        448      217               96.0   
3        1100              0       1746      324               88.0   
4        1925              0       3920      253               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay  Origin  Dest  Distance  \
0           150.0    116.0     -14.0       8.0      22    61       810   
1           145.0    113.0       2.0      19.0      22    61       810   
2            90.0     76.0      14.0       8.0      23    10       515   
3            90.0     78.0      -6.0      -4.0      23    10       515   
4            90.0     77.0      34.0      34.0      23    10       515   

   TaxiIn  TaxiOut  Cancelled  CancellationCode  Diverted  CarrierDelay  \
0     4.0      8.0          0                 0         0           0.0   
1     5.0     10.0          0                 0         0           0.0   
2     3.0     17.0          0                 0         0           0.0   
3     3.0      7.0          0                 0         0           0.0   
4     3.0     10.0          0                 0         0           2.0   

   WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay  
0           0.0       0.0            0.0                0.0  
1           0.0       0.0            0.0                0.0  
2           0.0       0.0            0.0                0.0  
3           0.0       0.0            0.0                0.0  
4           0.0       0.0            0.0               32.0

In [121]:
from sklearn.preprocessing import OneHotEncoder

In [203]:
onehot = OneHotEncoder(categorical_features='all', sparse=True)
onehot.fit(df2[['UniqueCarrier', 'TailNum']])
X = onehot.transform(df2[['UniqueCarrier', 'TailNum']])

In [179]:
X

<10000x502 sparse matrix of type '<type 'numpy.float64'>'
	with 20000 stored elements in Compressed Sparse Row format>

In [189]:
# print df2['TailNum'].num_unique  -> 502

In [180]:
print X

  (0, 414)	1.0
  (0, 0)	1.0
  (1, 471)	1.0
  (1, 0)	1.0
  (2, 218)	1.0
  (2, 0)	1.0
  (3, 325)	1.0
  (3, 0)	1.0
  (4, 254)	1.0
  (4, 0)	1.0
  (5, 426)	1.0
  (5, 0)	1.0
  (6, 462)	1.0
  (6, 0)	1.0
  (7, 218)	1.0
  (7, 0)	1.0
  (8, 396)	1.0
  (8, 0)	1.0
  (9, 359)	1.0
  (9, 0)	1.0
  (10, 397)	1.0
  (10, 0)	1.0
  (11, 130)	1.0
  (11, 0)	1.0
  (12, 265)	1.0
  :	:
  (9987, 0)	1.0
  (9988, 426)	1.0
  (9988, 0)	1.0
  (9989, 239)	1.0
  (9989, 0)	1.0
  (9990, 500)	1.0
  (9990, 0)	1.0
  (9991, 115)	1.0
  (9991, 0)	1.0
  (9992, 399)	1.0
  (9992, 0)	1.0
  (9993, 171)	1.0
  (9993, 0)	1.0
  (9994, 422)	1.0
  (9994, 0)	1.0
  (9995, 422)	1.0
  (9995, 0)	1.0
  (9996, 422)	1.0
  (9996, 0)	1.0
  (9997, 85)	1.0
  (9997, 0)	1.0
  (9998, 85)	1.0
  (9998, 0)	1.0
  (9999, 85)	1.0
  (9999, 0)	1.0


In [181]:
onehot = OneHotEncoder(categorical_features='all', sparse=False)
onehot.fit(df2[['UniqueCarrier', 'TailNum']])
X2 = onehot.transform(df2[['UniqueCarrier', 'TailNum']])

In [182]:
print X2

[[ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]]


In [183]:
df2.head(10)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0      1955.0   2211.0   
1  2008      1           3          4    754.0       735.0   1002.0   
2  2008      1           3          4    628.0       620.0    804.0   
3  2008      1           3          4    926.0       930.0   1054.0   
4  2008      1           3          4   1829.0      1755.0   1959.0   
5  2008      1           3          4   1940.0      1915.0   2121.0   
6  2008      1           3          4   1937.0      1830.0   2037.0   
7  2008      1           3          4   1039.0      1040.0   1132.0   
8  2008      1           3          4    617.0       615.0    652.0   
9  2008      1           3          4   1620.0      1620.0   1639.0   

   CRSArrTime  UniqueCarrier  FlightNum  TailNum  ActualElapsedTime  \
0      2225.0              0        335      413              128.0   
1      1000.0              0       3231      470              128.0   
2       750.0              0        448      217               96.0   
3      1100.0              0       1746      324               88.0   
4      1925.0              0       3920      253               90.0   
5      2110.0              0        378      425              101.0   
6      1940.0              0        509      461              240.0   
7      1150.0              0        535      217              233.0   
8       650.0              0         11      395               95.0   
9      1655.0              0        810      358               79.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay  Origin  Dest  Distance  \
0           150.0    116.0     -14.0       8.0      22    61     810.0   
1           145.0    113.0       2.0      19.0      22    61     810.0   
2            90.0     76.0      14.0       8.0      23    10     515.0   
3            90.0     78.0      -6.0      -4.0      23    10     515.0   
4            90.0     77.0      34.0      34.0      23    10     515.0   
5           115.0     87.0      11.0      25.0      23    26     688.0   
6           250.0    230.0      57.0      67.0      23    27    1591.0   
7           250.0    219.0     -18.0      -1.0      23    27    1591.0   
8            95.0     70.0       2.0       2.0      23    32     451.0   
9            95.0     70.0     -16.0       0.0      23    32     451.0   

   TaxiIn  TaxiOut  Cancelled  CancellationCode  Diverted  CarrierDelay  \
0     4.0      8.0          0                 0         0           0.0   
1     5.0     10.0          0                 0         0           0.0   
2     3.0     17.0          0                 0         0           0.0   
3     3.0      7.0          0                 0         0           0.0   
4     3.0     10.0          0                 0         0           2.0   
5     4.0     10.0          0                 0         0           0.0   
6     3.0      7.0          0                 0         0          10.0   
7     7.0      7.0          0                 0         0           0.0   
8     6.0     19.0          0                 0         0           0.0   
9     3.0      6.0          0                 0         0           0.0   

   WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay  
0           0.0       0.0            0.0                0.0  
1           0.0       0.0            0.0                0.0  
2           0.0       0.0            0.0                0.0  
3           0.0       0.0            0.0                0.0  
4           0.0       0.0            0.0               32.0  
5           0.0       0.0            0.0                0.0  
6           0.0       0.0            0.0               47.0  
7           0.0       0.0            0.0                0.0  
8           0.0       0.0            0.0                0.0  
9           0.0       0.0            0.0                0.0

In [208]:
onehot = OneHotEncoder(categorical_features=categoricalMask, sparse=True)
onehot.fit(df2)
Xall = onehot.transform(df2)

In [209]:
print Xall

  (0, 2535)	1.0
  (0, 2531)	1.0
  (0, 2529)	1.0
  (0, 2526)	1.0
  (0, 2423)	1.0
  (0, 2313)	1.0
  (0, 339)	1.0
  (0, 10)	1.0
  (0, 6)	1.0
  (0, 2)	1.0
  (0, 1)	1.0
  (0, 0)	1.0
  (1, 2535)	1.0
  (1, 2531)	1.0
  (1, 2529)	1.0
  (1, 2526)	1.0
  (1, 2423)	1.0
  (1, 2370)	1.0
  (1, 1678)	1.0
  (1, 10)	1.0
  (1, 6)	1.0
  (1, 2)	1.0
  (1, 1)	1.0
  (1, 0)	1.0
  (2, 2535)	1.0
  :	:
  (9998, 2537)	1549.0
  (9998, 2538)	1430.0
  (9998, 2539)	1706.0
  (9998, 2540)	1550.0
  (9998, 2541)	77.0
  (9998, 2542)	80.0
  (9998, 2543)	68.0
  (9998, 2544)	76.0
  (9998, 2545)	79.0
  (9998, 2546)	337.0
  (9998, 2547)	3.0
  (9998, 2548)	6.0
  (9998, 2550)	48.0
  (9998, 2553)	28.0
  (9999, 2537)	1050.0
  (9999, 2538)	1050.0
  (9999, 2539)	1211.0
  (9999, 2540)	1210.0
  (9999, 2541)	81.0
  (9999, 2542)	80.0
  (9999, 2543)	65.0
  (9999, 2544)	1.0
  (9999, 2546)	337.0
  (9999, 2547)	6.0
  (9999, 2548)	10.0


In [210]:
Xall.shape

(10000, 2554)

### Note that OneHot Encoder returns a sparse matrix

+ What is a sparse matrix?
A matrix where values that are 0s are not stored. 

In [211]:
##This is how big the dataset is

X.shape

(10000, 502)

### Assignment part I - 15 minutes

+ Using a subsection of the full dataset...
    - (otherwise it will be impossibly large)
    - Create interaction variables for month and ArrDelay
    - Note that Month must first be a dummy variable
    - There are many ways to do this

In [236]:
flights = df[['Month', 'ArrDelay']].head(10000).copy()

In [237]:
flights.head()

Month  ArrDelay
0      1     -14.0
1      1       2.0
2      1      14.0
3      1      -6.0
4      1      34.0

In [238]:
# Create 'dummy variable' for month?!

In [239]:
catMask = (flights.dtypes==np.int64).tolist()

catMask

[True, False]

In [326]:
onehot = OneHotEncoder(categorical_features=catMask, sparse=False)
onehot.fit(flights)

OneHotEncoder(categorical_features=[True, False],
       dtype=<type 'numpy.float64'>, handle_unknown='error',
       n_values='auto', sparse=False)

In [327]:
X = onehot.transform(flights)

In [328]:
X

array([[  1., -14.],
       [  1.,   2.],
       [  1.,  14.],
       ..., 
       [  1.,  89.],
       [  1.,  76.],
       [  1.,   1.]])

### Assignment Part II

+ Run a Ridge regression with month dummies, arrival delay and the interaction vars
+ Keep track of the coefficients by saving the names to a list
+ Which variables are larger than zero? 
+ How does your model perform on the testing set?

In [329]:
from sklearn.model_selection import train_test_split

test_size_in = 0.4

y0 = df2['ArrDelay']

In [330]:
# X = Xall
X = flights
# X = df2

In [331]:
X_train, X_test, y_train, y_test = train_test_split(X, y0, test_size=test_size_in, random_state=0)


In [332]:
from sklearn import linear_model
lr = linear_model.Ridge(normalize=True)

In [333]:
lr.fit(X_train, y_train)
pd.DataFrame({'features': flights.columns, 'coefficients': lr.coef_})

coefficients  features
0           0.0     Month
1           0.5  ArrDelay

In [334]:
lr.score(X_test, y_test)

0.74983094198887323

In [335]:
y2 = df2['Month']

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=test_size_in, random_state=0)

lr2 =  linear_model.Ridge(normalize=True)
lr2.fit(X_train, y_train)
lr2.coef_

array([ 0.,  0.])

In [336]:
lr2.score(X_test, y_test)

1.0

In [337]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(interaction_only=True)
poly

PolynomialFeatures(degree=2, include_bias=True, interaction_only=True)

In [338]:
poly.fit(flights)

PolynomialFeatures(degree=2, include_bias=True, interaction_only=True)

In [339]:
interactionY = poly.transform(flights)
interactionY 

array([[  1.,   1., -14., -14.],
       [  1.,   1.,   2.,   2.],
       [  1.,   1.,  14.,  14.],
       ..., 
       [  1.,   1.,  89.,  89.],
       [  1.,   1.,  76.,  76.],
       [  1.,   1.,   1.,   1.]])

In [340]:
y3 = interactionY

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=test_size_in, random_state=0)

lr3 =  linear_model.Ridge(normalize=True)
lr3.fit(X_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=True, random_state=None, solver='auto', tol=0.001)

In [341]:
lr3.score(X_test, y_test)

0.74983094198887179

In [342]:
lr3.coef_

array([[ 0. ,  0. ],
       [ 0. ,  0. ],
       [ 0. ,  0.5],
       [ 0. ,  0.5]])